// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetInitPath():Promise<string>;

export function OpenFileDialog():Promise<string>;

export function ReadFileBytes(arg1:string):Promise<string>;
