// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetInitPath() {
  return window['go']['main']['App']['GetInitPath']();
}

export function OpenFileDialog() {
  return window['go']['main']['App']['OpenFileDialog']();
}

export function ReadFileBytes(arg1) {
  return window['go']['main']['App']['ReadFileBytes'](arg1);
}
